"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SymbolVisibility = exports.SymbolKind = exports.getAffectedFilesForSymbol = exports.findAffectedCallSites = exports.registerPredictiveCompletion = exports.getFileDependents = exports.getFileDependencies = exports.quickSearchSymbols = exports.registerCodebaseChatParticipant = exports.queryCodebase = exports.disposeIndexWatcher = exports.startIndexWatcher = exports.getProjectIndex = exports.ensureProjectIndex = void 0;
var projectIndexer_1 = require("./projectIndexer");
Object.defineProperty(exports, "ensureProjectIndex", { enumerable: true, get: function () { return projectIndexer_1.ensureProjectIndex; } });
Object.defineProperty(exports, "getProjectIndex", { enumerable: true, get: function () { return projectIndexer_1.getProjectIndex; } });
Object.defineProperty(exports, "startIndexWatcher", { enumerable: true, get: function () { return projectIndexer_1.startIndexWatcher; } });
Object.defineProperty(exports, "disposeIndexWatcher", { enumerable: true, get: function () { return projectIndexer_1.disposeIndexWatcher; } });
var codebaseQuery_1 = require("./codebaseQuery");
Object.defineProperty(exports, "queryCodebase", { enumerable: true, get: function () { return codebaseQuery_1.queryCodebase; } });
Object.defineProperty(exports, "registerCodebaseChatParticipant", { enumerable: true, get: function () { return codebaseQuery_1.registerCodebaseChatParticipant; } });
Object.defineProperty(exports, "quickSearchSymbols", { enumerable: true, get: function () { return codebaseQuery_1.quickSearchSymbols; } });
Object.defineProperty(exports, "getFileDependencies", { enumerable: true, get: function () { return codebaseQuery_1.getFileDependencies; } });
Object.defineProperty(exports, "getFileDependents", { enumerable: true, get: function () { return codebaseQuery_1.getFileDependents; } });
var predictiveCompletion_1 = require("./predictiveCompletion");
Object.defineProperty(exports, "registerPredictiveCompletion", { enumerable: true, get: function () { return predictiveCompletion_1.registerPredictiveCompletion; } });
Object.defineProperty(exports, "findAffectedCallSites", { enumerable: true, get: function () { return predictiveCompletion_1.findAffectedCallSites; } });
Object.defineProperty(exports, "getAffectedFilesForSymbol", { enumerable: true, get: function () { return predictiveCompletion_1.getAffectedFilesForSymbol; } });
var types_1 = require("./types");
Object.defineProperty(exports, "SymbolKind", { enumerable: true, get: function () { return types_1.SymbolKind; } });
Object.defineProperty(exports, "SymbolVisibility", { enumerable: true, get: function () { return types_1.SymbolVisibility; } });
